
@baseUrl = http://localhost:4000

# get token using http://localhost:4000/login
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjY1OTg1NjE5LCJleHAiOjE2NjYwNzIwMTl9.IUU-xMABSig3ETuQHAHeOGLojcpfgRIVNzzAk51aj8c

###

# open in browser
GET {{baseUrl}}/login

###

GET {{baseUrl}}/tasks
Content-Type: application/json
Authorization: Bearer {{token}} 

###

POST {{baseUrl}}/tasks
Content-Type: application/json
Authorization: Bearer {{token}} 

{
  "title": "some task",
  "jiraId": "1",
  "description": "do something"
}

###

GET {{baseUrl}}/tasks/a0d4c60c-6429-4559-85b0-84f3a2385b1b
Content-Type: application/json
Authorization: Bearer {{token}} 

###

PATCH {{baseUrl}}/tasks/47e18eef-845c-4aab-9fcd-8c598249c25f
Content-Type: application/json 
Authorization: Bearer {{token}}

{
  "status": "done"
}

###

DELETE {{baseUrl}}/tasks/98c76c5a-157d-405f-96e7-b6c7fbf09cea
Authorization: Bearer {{token}}

###

POST {{baseUrl}}/tasks/assign
Content-Type: application/json
Authorization: Bearer {{token}} 

{}